---
- hosts: webserver
  become: true
  become_user: root
  tasks:
   - name: installing packages
     yum:
        name:
           - git
           - docker
   - name: start docker
     service: 
        name: docker
        state: started
     notify: enable docker
        
   - name: clone the repo 
     git:
        repo: https://github.com/Ram2305/E-commerce_application_deployment.git
        dest: /ec2-user
        
  handlers:
    - name: enable docker 
      service:
         name: docker
         enabled: yes
